char16_t* kapcBoHUDTextureNames[] = {
#ifdef REVENGE
	"AgressiveNeg",
	"AgressivePos",
	"TakeDownNeg",
	"TakeDownPos",
	"RatingDown",
	"RatingUp",
	"Crash",
	"CrashBreaker",
	"pickup_multiplier_skull",
	"pickup_score01",
	"pickup_score02",
	"pickup_score03",
	"analogueStick_direction",
	"analogueStick",
	"controller",
	"anchor",
	"chev_sml",
	"road_tile",
	"border_tile",
	"box_end",
	"box_tile",
	"medal_gold",
	"medal_silver",
	"medal_bronze",
	"ta_bg_end",
	"ta_bg_tile",
	"ta_fuse_glow",
	"ta_fuse_tile",
	"stars_stroke",
	"star_corona",
	"BoostGlowBits",
	"CrashBar",
	"TalkIcon",
	"CrossIcon",
	"star_empty",
	"star_full",
	"L1Button",
	"L2Button",
	"R1Button",
	"R2Button",
	"CrossButton"
#elif DOMINATOR
	"Crash"
	"analogueStick_direction"
	"analogueStick"
	"controller"
	"anchor"
	"chev_sml"
	"Border_Gradient"
	"Damage_01"
	"Damage_02"
	"Damage_03"
	"box_end"
	"box_tile"
	"medal_gold"
	"medal_silver"
	"medal_bronze"
	"ta_bg_end"
	"ta_bg_tile"
	"ta_fuse_glow"
	"ta_fuse_tile"
	"stars_stroke"
	"star_corona"
	"CrossIcon"
	"star_empty"
	"star_fill"
	"Arrow"
	"Boost_Arrow"
	"Boost_Corner_Dirt"
	"Boost_Gradient_Overlay"
	"Central_Gradient"
	"Central_Line"
	"Gradient"
	"Large_Gradient"
	"Line_Edge_Dirt"
	"Outline_Gradient_Line"
	"Outline_Tip"
	"Icon_64x64"
	"positive"
	"negative"
	"Takedown"
	"Crashed"
	"BoostGained"
	"star_fill_stamp"
	"Drift"
	"NearMiss"
	"Single_Bar"
	"Double_Bar"
	"White_Line"
	"L1Button"
	"L2Button"
	"R1Button"
	"R2Button"
	"CrossButton"
#endif
};