#ifndef BOVEHICLEWORLDTRIANGLECACHEMANAGER_H
#define BOVEHICLEWORLDTRIANGLECACHEMANAGER_H

class CBoWorldTriangleCacheBase {

};

class CBoVehicleWorldTriangleCache {

};

#endif // !#define BOVEHICLEWORLDTRIANGLECACHEMANAGER_H

